export const CLAIMS = [
  {
    id: "CG-2024-00142",
    memberId: "M-88421",
    memberName: "Robert Harmon",
    age: 71, gender: "M",
    providerId: "PRV-3301",
    providerName: "Dr. Sarah Nguyen",
    specialty: "Primary Care",
    facility: "Riverside Family Medicine",
    city: "Austin", state: "TX",
    serviceDate: "2024-10-03",
    serviceTime: "10:00 AM",
    procedureCode: "99213",
    procedureDesc: "Office Visit - Established Patient, Low Complexity",
    diagnosisCode: "Z00.00",
    diagnosisDesc: "Routine General Medical Examination",
    anomalyType: "NONE",
    riskLevel: "LOW",
    status: "AUTO-CLEARED",
    flagReason: null,
    signal: "No anomalies detected",
    memberHistory: []
  },
  {
    id: "CG-2024-00587A",
    memberId: "M-44219",
    memberName: "Gloria Esteves",
    age: 68, gender: "F",
    providerId: "PRV-1142",
    providerName: "Dr. James Polk",
    specialty: "Cardiology",
    facility: "Lakewood Heart Center",
    city: "Denver", state: "CO",
    serviceDate: "2024-11-14",
    serviceTime: "9:00 AM",
    procedureCode: "93000",
    procedureDesc: "Electrocardiogram (ECG)",
    diagnosisCode: "I10",
    diagnosisDesc: "Essential Hypertension",
    anomalyType: "LOCATION CONFLICT",
    riskLevel: "HIGH",
    riskColor: "red",
    status: "PENDING REVIEW",
    signal: "Same-day location impossibility",
    pairedClaimId: "CG-2024-00587B",
    distanceMiles: 1698,
    location1: { label: "9:00 AM — Lakewood Heart Center", city: "Denver", state: "CO", lat: 39.7, lng: -104.9 },
    location2: { label: "11:30 AM — Suncoast Medical Group", city: "Tampa", state: "FL", lat: 27.9, lng: -82.4 },
    flagReason: "Member M-44219 has two claims on the same date from facilities 1,698 miles apart with a 2.5-hour service window. Physical presence at both locations is not clinically possible. Flagged for reviewer investigation.",
    memberHistory: []
  },
  {
    id: "CG-2024-00587B",
    memberId: "M-44219",
    memberName: "Gloria Esteves",
    age: 68, gender: "F",
    providerId: "PRV-2278",
    providerName: "Dr. Anita Reyes",
    specialty: "Internal Medicine",
    facility: "Suncoast Medical Group",
    city: "Tampa", state: "FL",
    serviceDate: "2024-11-14",
    serviceTime: "11:30 AM",
    procedureCode: "99214",
    procedureDesc: "Office Visit - Established Patient, Moderate Complexity",
    diagnosisCode: "I10",
    diagnosisDesc: "Essential Hypertension",
    anomalyType: "LOCATION CONFLICT",
    riskLevel: "HIGH",
    riskColor: "red",
    status: "PENDING REVIEW",
    signal: "Paired location conflict claim",
    pairedClaimId: "CG-2024-00587A",
    flagReason: "Paired claim to CG-2024-00587A. Same member, same date, second location Tampa FL. Reviewed together as a location conflict cluster.",
    memberHistory: []
  },
  {
    id: "CG-2024-00934",
    memberId: "M-61033",
    memberName: "David Kwan",
    age: 74, gender: "M",
    providerId: "PRV-4455",
    providerName: "Dr. Marcus Bell",
    specialty: "Endocrinology",
    facility: "Pinecrest Specialty Clinic",
    city: "Nashville", state: "TN",
    serviceDate: "2024-12-02",
    serviceTime: "2:15 PM",
    procedureCode: "99215",
    procedureDesc: "Office Visit - Established Patient, High Complexity",
    diagnosisCode: "E11.649",
    diagnosisDesc: "Type 2 Diabetes with Hypoglycemia (HCC 18)",
    anomalyType: "HCC ANOMALY",
    riskLevel: "HIGH",
    riskColor: "amber",
    status: "PENDING REVIEW",
    signal: "Unsupported HCC 18 submission",
    providerHCCRate: "4.2x above peer average",
    flagReason: "Diagnosis code E11.649 (Type 2 Diabetes with Hypoglycemia) submitted for member M-61033 is not supported by 24 months of longitudinal claim history. No prior diabetes diagnosis, A1C labs, or endocrinology encounters on record. Submitting provider HCC 18/19 rate is 4.2x above peer cohort average. Flagged for medical record review before encounter submission.",
    memberHistory: [
      { date: "2022-11-08", provider: "Dr. Lisa Park - PCP", code: "99213", diagnosis: "Z00.00", desc: "Routine General Medical Exam", flagged: false },
      { date: "2023-02-14", provider: "Dr. Lisa Park - PCP", code: "99213", diagnosis: "Z12.11", desc: "Screening for Colon Cancer", flagged: false },
      { date: "2023-06-21", provider: "Dr. Lisa Park - PCP", code: "99213", diagnosis: "Z00.00", desc: "Routine General Medical Exam", flagged: false },
      { date: "2023-09-05", provider: "Dr. Lisa Park - PCP", code: "99213", diagnosis: "R73.09", desc: "Other Abnormal Glucose (borderline - NOT HCC)", flagged: false },
      { date: "2023-11-30", provider: "Dr. Lisa Park - PCP", code: "99213", diagnosis: "Z00.00", desc: "Routine General Medical Exam", flagged: false },
      { date: "2024-03-12", provider: "Dr. Lisa Park - PCP", code: "99213", diagnosis: "Z12.11", desc: "Screening for Colon Cancer", flagged: false },
      { date: "2024-07-18", provider: "Dr. Lisa Park - PCP", code: "99213", diagnosis: "Z00.00", desc: "Routine General Medical Exam", flagged: false },
      { date: "2024-12-02", provider: "Dr. Marcus Bell - Endocrinology", code: "99215", diagnosis: "E11.649", desc: "Type 2 Diabetes with Hypoglycemia (HCC 18) - FLAGGED", flagged: true }
    ]
  }
];

